# config.yaml
#
# log
#   path: 日志文件保存的目录
#   name: 日志文件前缀名
#   ext: 日志文件后缀名
#   time-format: 日志文件名时间格式
#   debug: 是否开启调试模式，当开启调试模式时，记录日志文件名称和行并不会过滤 DEBUG WARN 类型日志

log:
    path: logs
    name: docker-protector
    ext: log
    time-format: 2006-01-02
    debug: true